// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  button: dynamic(() => import("./Button")),
  rich_text: dynamic(() => import("./RichText")),
  swiper: dynamic(() => import("./Swiper")),
};
